### PR TITLE
texture filtering bits

### PR DESCRIPTION
**Pull request by digetx**

### CODE REVIEW

**Comment by digetx** [comment]
https://github.com/grate-driver/grate/pull/31

**Comment by kusma** [comment]
I'm having a hard time understanding what the "within" and "between"-things here mean...

**Comment by kusma** [comment]
I have a feeling that one of them (`min_filter_linear_within`?) offset the cutoff-point between min and mag filtering by 0.5, though. That's kind of an awkward opengl texture filtering-detail...

**Comment by digetx** [comment]
I used "within" and "between" notations from https://www.khronos.org/opengl/wiki/Sampler_Object

**Comment by digetx** [comment]
Maybe adding a postfix will make them more obvious? Like this:

	MINFILTER_LINEAR_WITHIN_MIPLEVEL
	MINFILTER_LINEAR_BETWEEN_MIPLEVELS

**Comment by digetx** [comment]
BTW, please take a look at texture-filter grate test to see what those bits do :) I *think* that I've got it all correct.

**Comment by kusma** [comment]
Aha, then I think I understand. Yeah, OK, this is not what I thought, with the 0.5 threshold. Looks fine as-is to me.

**Pull request merged**
